##########################
# Basic configurations   #
##########################

debug: false

# Website info
title: Algviz

description:
  cn: 让你的 Python 代码能够输出可视化的算法运行过程的动画演示！
  en: Bring alive animations into your Python code.

keywords:
  cn: 算法可视化 Python 数据结构 动画演示
  en: Algorithm visualization Python animation data structure

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://algviz.com"
lang: zh    # options: [zh, en]
timezone: Asia/Shanghai
encoding: "utf-8"

# Author info
github_username:  zjl9959
repository: zjl9959/algviz.com
since: 2022-2023
author: zjl9959
email: zjl9959@gmail.com
subscribe_rss: /feed.xml

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

compress_html:
  clippings: all
  comments: ["<!--", "-->"]

collections:
  en:
    permalink: /en/:title/
    output: true
  cn:
    permalink: /cn/:title/
    output: true

# How many blogs showed in one page
pagination:
  enabled: true
  per_page: 5
  collection: cn, en
  sort_field: 'date'
  sort_reverse: true

cdn:
    jsdeliver:
        enabled: true
    svg_repo: zjl9959/algviz-launch

#############################
#  Plugins configurations   #
#############################
simple_jekyll_search:
    fulltext: false
    limit: 5

# Markdown
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
highlighter: rouge


#####################
#    Navigation     #
#####################
navs:
  cn:
    -
      href: /index.html
      label: 主页

    -
      href: /cn/index.html
      label: 博客

    -
      href: /cn/sponsor.html
      label: 赞助
  en:
    -
      href: /index_en.html
      label: Home

    -
      href: /en/index.html
      label: Blog

    -
      href: /en/sponsor.html
      label: Donate


####################
#    Components    #
####################
components:
    word_count:
        enabled: true

    share:
        enabled: true


###################
#    Google       #
###################
google:
  analytics:
    enabled: true
    id: G-4Z0KQSTDLS
