##########################
# Basic configurations   #
##########################

# Website info
title: Algviz
description: >- # this means to ignore newlines until "baseurl:"
  Bring alive animations into your code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://algviz.com"
lang: zh    # options: [zh, en]
timezone: Asia/Shanghai
encoding: "utf-8"

# Author info
github_username:  zjl9959
repository: zjl9959/algviz.com
since: 2022
author: zjl9959
email: zjl9959@gmail.com
subscribe_rss: /feed.xml

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

compress_html:
  clippings: all
  comments: ["<!--", "-->"]

collections:
  en:
    permalink: /en/:title/
    output: true
  cn:
    permalink: /cn/:title/
    output: true

# How many blogs showed in one page
pagination:
  enabled: true
  per_page: 5
  collection: cn
  permalink: '/cn/:title/'

cdn:
    jsdelivr:
        enabled: false
    svg_repo: zjl9959/algviz-launch

#############################
#  Plugins configurations   #
#############################
simple_jekyll_search:
    fulltext: false
    limit: 5

# Markdown
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
highlighter: rouge


#####################
#    Navigation     #
#####################
navs:
  cn:
    -
      href: /index.html
      label: 主页

    -
      href: /cn/about.html
      label: 关于
  en:
    -
      href: /en/index.html
      label: Home

    -
      href: /en/about.html
      label: About


####################
#    Components    #
####################
components:
    word_count:
        enabled: true


###################
#    Google       #
###################
google:
  analytics:
    enabled: false
    id: G-4Z0KQSTDLS
