# This is a basic workflow to help you get started with Actions

name: Deploy algviz.com

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.117.0
        with:
          ruby-version: 2.6
          bundler-cache: true

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          bundler install
      
      # Build the website
      - name: Build algviz.com
        run: |
          bundle exec jekyll build
          
      - name: Deploy gh-pages
        uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          source-directory: _site
          deploy-branch: gh-pages
          
